version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Starting install phase..."
      - npm install -g @angular/cli
      - echo "Install phase completed"
  
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 061039764011.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Pre-build configuration completed"
      - echo "Image tag - $IMAGE_TAG"
  
  build:
    commands:
      - echo "Building the Docker image..."
      - echo "Current directory contents:"
      - ls -la
      - docker build -t finplay-angular-app .
      - docker tag finplay-angular-app:latest 061039764011.dkr.ecr.us-east-1.amazonaws.com/finplay-angular-app:latest
  
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push 061039764011.dkr.ecr.us-east-1.amazonaws.com/finplay-angular-app:latest
      - echo "Writing image definitions file..."
      - printf '{"ImageURI":"%s"}' 061039764011.dkr.ecr.us-east-1.amazonaws.com/finplay-angular-app:latest > imageDefinitions.json
      - aws ecs update-service --cluster finplay-cluster --service finplay-flask-service --force-new-deployment --region us-east-1
      - echo "Post-build phase completed"

artifacts:
  files:
    - imageDefinitions.json

cache:
  paths:
    - '/root/.npm/**/*'